<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Navbar Layout</title>

<link rel="stylesheet" href="style.css">

</head>

<body>

<!-- Navbar 1 -->

<div class="navbar">

<div class="logo">LOGOBAKERY</div>

<ul class="menu">
<li><a href="#">Services</a></li>
<li><a href="#">Projects</a></li>
<li><a href="#">About</a></li>
</ul>

<a href="#" class="btn">Contact</a>

</div>


<!-- Navbar 2 -->

<div class="navbar">

<ul class="menu left">
<li><a href="#">Services</a></li>
<li><a href="#">Projects</a></li>
<li><a href="#">About</a></li>
</ul>

<a href="#" class="btn">Contact</a>

<div class="logo">LOGOBAKERY</div>

</div>


<!-- Navbar 3 -->

<div class="navbar">

<div class="logo">LOGOBAKERY</div>

<ul class="menu right">
<li><a href="#">Services</a></li>
<li><a href="#">Projects</a></li>
<li><a href="#">About</a></li>
<li><a class="btn inside" href="#">Contact</a></li>
</ul>

</div>

</body>
